variables:
  CI: 'false'
  IMAGE_NAME: $CI_REGISTRY_IMAGE
  DOCKERFILE_PATH: './FraudDetection.WebApp/Dockerfile'
  APPSETTINGS_PATH: './FraudDetection.WebApp'

stages:
  - build image
  - deployment

dev_build_image:
  image: docker:latest
  stage: build image
  services:
    - docker:dind
  before_script:
    - 'docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY'
  script:
    - 'cd $APPSETTINGS_PATH'
    - 'echo $AppsettingsDevelopment > appsettings.Development.json'
    - 'cd ..'
    - 'docker build -t $IMAGE_NAME:dev -f $DOCKERFILE_PATH .'
    - 'docker push $IMAGE_NAME:dev'
  only:
    - main